version: '3.8'

services:
  postgres:
    image: 'postgres:13.1'
    environment:
      POSTGRES_USER: 'app'
      POSTGRES_PASSWORD: 'sample123'
      POSTGRES_DB: 'interview_project_dev'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
